services:
  postgres-primary:
    container_name: postgres-primary
    image: postgres
    volumes: # <volume_or_directory_on_host>:<path_in_container>
      - postgres-volume-primary:/var/lib/postgresql/ # database persistency
      - ./init-scripts/primary:/docker-entrypoint-initdb.d # autorunning initialization scripts
    networks:
      - postgres_network # container communication
    environment:
      POSTGRES_USER: primary # superuser name
      POSTGRES_PASSWORD: pw # superuser password

    healthcheck: # check if database is up
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      start_period: 4s
      start_interval: 1s
      interval: 1s
      retries: 5 
      timeout: 5s


  postgres-replica1:
    build:
      context: .
      dockerfile: docker/replica/Dockerfile
    container_name: postgres-replica1
    depends_on:
      postgres-primary:
        condition:
          service_healthy # wait for postgres-primary healtcheck
        restart: true
    volumes:
      # - postgres-volume-replica1:/var/lib/postgresql/
      - ./ssh/authorized_keys:/var/lib/postgresql/.ssh/authorized_keys
      # - ./ssh/authorized_keys:/root/.ssh/authorized_keys
    networks:
      - postgres_network
    environment:
      PGUSER: replicator # connection user
      PGPASSWORD: replicator_password # connection password
      POSTGRES_USER: rep1 # superuser name
      POSTGRES_PASSWORD: rep1_pw # superuser password
    healthcheck: # check if database is up
      test: ["CMD-SHELL", "pg_isready -U primary"]
      start_period: 4s
      start_interval: 1s
      interval: 1s
      retries: 5 
      timeout: 5s


  postgres-replica2:
    container_name: postgres-replica2
    build:
      context: .
      dockerfile: docker/replica/Dockerfile
    depends_on:
      postgres-primary:
        condition:
          service_healthy
        restart: true
    volumes:
      - ./ssh/authorized_keys:/var/lib/postgresql/.ssh/authorized_keys
      # - postgres-volume-replica2:/var/lib/postgresql/
      # - ./ssh/authorized_keys:/root/.ssh/authorized_keys
    networks:
      - postgres_network
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
      POSTGRES_USER: rep2
      POSTGRES_PASSWORD: rep2_pw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primary"]
      start_period: 4s
      start_interval: 1s
      interval: 1s
      retries: 5 
      timeout: 5s

  pgpool:
    container_name: pgpool
    # image: pgpool/pgpool
    build:
      context: .
      dockerfile: docker/pgpool-ssh/Dockerfile
    depends_on:
      postgres-primary:
        condition:
          service_healthy
        restart: true
      postgres-replica1:
        condition:
          service_healthy
        restart: true
      postgres-replica2:
        condition:
          service_healthy
        restart: true
    volumes:
      - ./init-scripts/pgpool:/config:ro
      - ./ssh/id_rsa_pgpool:/var/lib/pgsql/.ssh/id_rsa_pgpool
    networks:
      - postgres_network
    ports:
      - 5432:9999 # map localhost 5432(postgres) to 9999 (pgpool) on pgpool container

volumes:
  postgres-volume-primary:
  postgres-volume-replica1:
  postgres-volume-replica2:

networks:
  postgres_network:

